whitelistPackagePrefixes:
- com.unity3d
- bolts
- com.hp
- butterknife
- dagger
- anywheresoftware
- kawa
- twitter4j
- org.telegram
- io.reactivex
- com.fasterxml
- com.amazon
- com.vungle
- com.mopub
- com.amazonaws
- com.crashlytics
- com.umeng
- com.inmobi
- com.tapjoy
- com.aipai
- io.fabric
- com.searchboxsdk
- com.github
- com.yandex
- com.hp
- com.adobe
- com.alibaba
- android.support
- android.graphics
- android.widget
- com.google.android
- com.google.gson
- com.google.firebase
- com.alibaba
- org.apache
- com.facebook
- org.jboss
- com.adobe
- com.zipwhip
- rx.internal
- com.startapp
- com.searchboxsdk
- com.flurry
- com.ibingo
- org.spongycastle
- ch.boye
- com.getkeepsafe
- com.tencent
- com.virgo
- com.evernote
- com.bumptech
- twitter4j
- com.mercuryintermedia
- com.nineoldandroids
- com.pushio
- com.sony
- com.sun
- com.fasterxml
- org.json
- okio
- org.jsoup
- com.squareup
- android.animation
- com.firebase
- cz.msebera
- com.mega4tech
- org.jsoup
- org.greenrobot
- androidx
- android.arch
- android.databinding
- okhttp3
- retrofit2
- java
adPackagePrefixes:
- com.admarvel
- com.admob
- mediba.ad.sdk
- com.admob.android
- com.mopub.mobileads
- com.google.ads
- com.aduwant.ads
- com.inneractive.api.ads
- com.smartadserver.android
- com.swelen.ads
- com.adsdk.sdk
- com.applift.playads
- de.selfadservice
- com.revmob.ads
- android.support
- com.millennialmedia
- com.flurry
- com.inmobi
- com.nexage
- com.jumptap
- com.google.analytics
- com.tapjoy
