#!/bin/bash
set -e
set -x

export JAVA_OPTS="-Xms512m -Xmx4G"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
apk=$(realpath $1)
spec=$(realpath $2)
out=$(realpath $3)
cd $DIR

if [ -z "$BATCH_RUN" ]; then
    make jar
fi
java -jar target/scala-2.13/liquid-assembly-0.1.jar --apk $apk --spec $spec --out $out $LIQUID_FLAGS
