name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check out android-platforms
      run: git clone https://github.com/izgzhen/android-platforms
    - name: Cache sbt
      uses: actions/cache@v1
      with:
        path: "~/.sbt"
        key: ${{ runner.os }}-node-${{ hashFiles('**/build.sbt') }}
    - name: Build test dependencies
      run: make test
    - name: Run unit tests
      run: sbt test
